### ISSUE TITLE
TypeError: stack.hasAll is not a function

### ISSUE THREAD

**Issue by justinr1234** [sysgears/spin.js#1]
Note: not part of starter kit, but after merging in your latest spin changes I'm having issues.

**Update** Having issue with starter kit too

```
yarn watch v0.27.5
$ spin watch
TypeError: stack.hasAll is not a function
    at WebAssetsPlugin.configure (/Users/justin/bv/ironworks_2/iron-works/node_modules/spinjs/src/plugins/WebAssetsPlugin.ts:9:19)
    at /Users/justin/bv/ironworks_2/iron-works/node_modules/spinjs/src/spin.config.ts:68:69
    at Array.forEach (native)
    at _loop_1 (/Users/justin/bv/ironworks_2/iron-works/node_modules/spinjs/src/spin.config.ts:68:28)
    at createConfig (/Users/justin/bv/ironworks_2/iron-works/node_modules/spinjs/lib/spin.config.js:75:13)
    at Object.exports.default (/Users/justin/bv/ironworks_2/iron-works/node_modules/spinjs/src/createConfig.ts:11:12)
    at Object.<anonymous> (/Users/justin/bv/ironworks_2/iron-works/node_modules/spinjs/src/index.ts:18:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
TypeError: Cannot read property 'name' of undefined
    at /Users/justin/bv/ironworks_2/iron-works/node_modules/spinjs/src/executor.ts:552:53
    at buildDll (/Users/justin/bv/ironworks_2/iron-works/node_modules/spinjs/src/executor.ts:550:12)
    at _loop_1 (/Users/justin/bv/ironworks_2/iron-works/node_modules/spinjs/src/executor.ts:786:21)
    at /Users/justin/bv/ironworks_2/iron-works/node_modules/spinjs/lib/executor.js:849:17
TypeError: Cannot read property 'name' of undefined
    at /Users/justin/bv/ironworks_2/iron-works/node_modules/spinjs/src/executor.ts:552:53
    at buildDll (/Users/justin/bv/ironworks_2/iron-works/node_modules/spinjs/src/executor.ts:550:12)
    at _loop_1 (/Users/justin/bv/ironworks_2/iron-works/node_modules/spinjs/src/executor.ts:786:21)
    at /Users/justin/bv/ironworks_2/iron-works/node_modules/spinjs/lib/executor.js:849:17
webpack-for-server Time: 146ms

ERROR in ./src/server/api_server.js
Module parse failed: /Users/justin/bv/ironworks_2/iron-works/src/server/api_server.js Unexpected token (52:12)
You may need an appropriate loader to handle this file type.
|           return {
|             query: invertedMap[body.id],
|             ...body
|           };
|         });
 @ ./src/server/index.js 2:0-22
 @ multi ./src/server/index.js webpack/hot/signal.js
```

**Comment by justinr1234** [comment]
@vlasenko The node module doesn't have the proper definition for the `Stack` class:

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Stack = (function () {
    function Stack() {
        var stack = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            stack[_i] = arguments[_i];
        }
        this.technologies = stack.reduce(function (acc, tech) {
            if (!tech) {
                return acc;
            }
            else if (tech.constructor === Array) {
                return acc.concat(tech);
            }
            else {
                return acc.concat(tech.split(':'));
            }
        }, []);
        if (this.hasAny('server')) {
            this.platform = 'server';
        }
        else if (this.hasAny('web')) {
            this.platform = 'web';
        }
        else if (this.hasAny('android')) {
            this.platform = 'android';
        }
        else if (this.hasAny('ios')) {
            this.platform = 'ios';
        }
    }
    Stack.prototype.hasAny = function (arg) {
        var array = arg.constructor === Array ? arg : [arg];
        for (var _i = 0, array_1 = array; _i < array_1.length; _i++) {
            var feature = array_1[_i];
            if (this.technologies.indexOf(feature) >= 0) {
                return true;
            }
        }
        return false;
    };
    return Stack;
}());
exports.default = Stack;
//# sourceMappingURL=stack.js.map
```

**Comment by vlasenko** [comment]
@justinr1234 Looks like you are using outdated version? When I install version `0.1.15`, which is the latest, I have `hasAll` function in `Stack` class

**Comment by mitjade** [comment]
@vlasenko Same problem seems to accrue in the kit.

**Comment by vlasenko** [comment]
@mitjade I don't see it. Could you check what version of `spin.js` is used in `node_modules/spinjs` ?

**Comment by mitjade** [comment]
`0.1.15`

**Comment by mitjade** [comment]
Also tried now with `0.1.16`. Same result. Using `Mac`.

**Comment by vlasenko** [comment]
@mitjade How can it be? Does `Stack` has no `hasAll` function in `0.1.16` ?

**Comment by mitjade** [comment]
Mine has.

**Comment by mitjade** [comment]
```
export default class Stack {
    technologies: string[];
    platform: string;

    constructor(...stack) {
        this.technologies = stack.reduce((acc, tech) => {
            if (!tech) {
                return acc;
            } else if (tech.constructor === Array) {
                return acc.concat(tech);
            } else {
                return acc.concat(tech.split(':'));
            }
        }, []);
        if (this.hasAny('server')) {
            this.platform = 'server';
        } else if (this.hasAny('web')) {
            this.platform = 'web';
        } else if (this.hasAny('android')) {
            this.platform = 'android';
        } else if (this.hasAny('ios')) {
            this.platform = 'ios';
        }
    }

    hasAny(technologies): Boolean {
        const array = technologies.constructor === Array ? technologies : [technologies];
        for (let feature of array) {
            if (this.technologies.indexOf(feature) >= 0) {
                return true;
            }
        }
        return false;
    }

    hasAll(technologies): Boolean {
        const array = technologies.constructor === Array ? technologies : [technologies];
        for (let feature of array) {
            if (this.technologies.indexOf(feature) < 0) {
                return false;
            }
        }
        return true;
    }
}

```

**Comment by mitjade** [comment]
```
{
  "name": "spinjs",
  "version": "0.1.16",
  "scripts": {
    "compile": "tsc",
    "watch": "tsc -w",
    "lint": "tslint --fix 'src/*.ts*' -p tsconfig.json --type-check && tslint 'test/*.ts*' -p tsconfig.json --type-check",
    "test": " ",
    "prepublish": "npm run compile"
  },
  "files": [
    "src",
    "lib",
    "spin.config.js",
    "spin.js",
    "webpack.config.js"
  ],
  "bin": {
    "spin": "./spin.js"
  },
  "devDependencies": {
    "@types/ip": "^0.0.30",
    "@types/lodash": "^4.14.71",
    "@types/mkdirp": "^0.5.0",
    "@types/node": "^7.0.18",
    "@types/webpack-merge": "^0.0.5",
    "@types/webpack-sources": "^0.1.2",
    "@types/yargs": "^8.0.2",
    "tslint": "^5.2.0",
    "typescript": "^2.4.1"
  },
  "dependencies": {
    "ip": "^1.1.5",
    "lodash": "^4.17.4",
    "minilog": "^3.1.0",
    "mkdirp": "^0.5.1",
    "source-list-map": "^2.0.0",
    "source-map-support": "^0.4.15",
    "webpack-merge": "^4.1.0",
    "webpack-sources": "^1.0.1",
    "yargs": "^8.0.2"
  }
}
```

**Comment by mitjade** [comment]
Am I looking in the wrong place?

**Comment by vlasenko** [comment]
@mitjade What is inside `lib/Stack.js` ?

**Comment by mitjade** [comment]
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Stack = (function () {
    function Stack() {
        var stack = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            stack[_i] = arguments[_i];
        }
        this.technologies = stack.reduce(function (acc, tech) {
            if (!tech) {
                return acc;
            }
            else if (tech.constructor === Array) {
                return acc.concat(tech);
            }
            else {
                return acc.concat(tech.split(':'));
            }
        }, []);
        if (this.hasAny('server')) {
            this.platform = 'server';
        }
        else if (this.hasAny('web')) {
            this.platform = 'web';
        }
        else if (this.hasAny('android')) {
            this.platform = 'android';
        }
        else if (this.hasAny('ios')) {
            this.platform = 'ios';
        }
    }
    Stack.prototype.hasAny = function (arg) {
        var array = arg.constructor === Array ? arg : [arg];
        for (var _i = 0, array_1 = array; _i < array_1.length; _i++) {
            var feature = array_1[_i];
            if (this.technologies.indexOf(feature) >= 0) {
                return true;
            }
        }
        return false;
    };
    return Stack;
}());
exports.default = Stack;
//# sourceMappingURL=stack.js.map
```

**Comment by mitjade** [comment]
`typescript` problem?

**Comment by vlasenko** [comment]
@mitjade I have just created empty project `test`, with `npm init`, then installed `spinjs` via `npm i spinjs@0.1.16` and my `lib/Stack.js` has `hasAll` function, as expected

**Comment by vlasenko** [comment]
@mitjade I'm not sure what the problem is, I can't reproduce it

**Comment by mitjade** [comment]
@vlasenko Done the same with empty project no `hasAll`?

**Comment by vlasenko** [comment]
@mitjade Haha

**Comment by vlasenko** [comment]
@mitjade Okay, let me release 0.2.0 maybe

**Comment by vlasenko** [comment]
@mitjade Published `0.2.0`, could check whether `0.2.0` has `hasAll` in `lib/Stack.js` ?

**Comment by mitjade** [comment]
@vlasenko It does. What just happened?

**Comment by vlasenko** [comment]
@mitjade I don't know. I have just increased minor version, so that it become `0.2.0`

**Comment by mitjade** [comment]
@vlasenko kit also works ok now

**Comment by vlasenko** [comment]
@mitjade Good to know, thanks for helping to debug this issue

**Comment by vlasenko** [comment]
@mitjade Thought I still don't understand what was the cause of this problem, but I'm glad it is gone for you

**Comment by mitjade** [comment]
@vlasenko hopefully it will also work for @justinr1234 and @MichelDiz.

**Comment by justinr1234** [comment]
@vlasenko What version of npm?   @mitjade same question

**Comment by vlasenko** [comment]
@justinr1234 
```
$ npm --version
5.0.3
```

**Comment by justinr1234** [comment]
@vlasenko I'm not sure what you're doing that's creating the actual package, but the 2 broken versions absolutely have the wrong output in `/lib`. What generates the `/lib` folder?

https://registry.npmjs.org/spinjs/-/spinjs-0.1.15.tgz

https://registry.npmjs.org/spinjs/-/spinjs-0.1.16.tgz

**Comment by vlasenko** [comment]
@justinr1234 I have just downloaded and checked both these archives. And both have correct output in `lib/Stack.js`, e.g. it has `hasAll` function.

**Comment by vlasenko** [comment]
@justinr1234 Yes

**Comment by vlasenko** [comment]
@justinr1234 
The size of spinjs-0.1.15.tgz is 61143 bytes. The MD5 sum is:
```
$ md5sum spinjs-0.1.15.tgz 
557c9704e0a57b6f4454a383935cfce1  spinjs-0.1.15.tgz
```

**Comment by justinr1234** [comment]
@vlasenko  Same info on my end --- now I'm really confused

**Comment by justinr1234** [comment]
@vlasenko Just had my friend in Taiwan check (I'm in the US) and he doesn't see `hasAll` either

**Comment by vlasenko** [comment]
@justinr1234 What is md5sum of spinjs-0.1.15.tgz  that you have downloaded via browser?

**Comment by justinr1234** [comment]
```
md5 spinjs-0.1.15.tgz
MD5 (spinjs-0.1.15.tgz) = 557c9704e0a57b6f4454a383935cfce1
```

**Comment by vlasenko** [comment]
@justinr1234 If we have the same md5sum we can't have different contents :)

**Comment by justinr1234** [comment]
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Stack = (function () {
    function Stack() {
        var stack = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            stack[_i] = arguments[_i];
        }
        this.technologies = stack.reduce(function (acc, tech) {
            if (!tech) {
                return acc;
            }
            else if (tech.constructor === Array) {
                return acc.concat(tech);
            }
            else {
                return acc.concat(tech.split(':'));
            }
        }, []);
        if (this.hasAny('server')) {
            this.platform = 'server';
        }
        else if (this.hasAny('web')) {
            this.platform = 'web';
        }
        else if (this.hasAny('android')) {
            this.platform = 'android';
        }
        else if (this.hasAny('ios')) {
            this.platform = 'ios';
        }
    }
    Stack.prototype.hasAny = function (arg) {
        var array = arg.constructor === Array ? arg : [arg];
        for (var _i = 0, array_1 = array; _i < array_1.length; _i++) {
            var feature = array_1[_i];
            if (this.technologies.indexOf(feature) >= 0) {
                return true;
            }
        }
        return false;
    };
    return Stack;
}());
exports.default = Stack;
```

```
md5 spinjs-0.1.15.tgz 
MD5 (spinjs-0.1.15.tgz) = 557c9704e0a57b6f4454a383935cfce1
```

http://recordit.co/5Z3WAmDIvy/gif/notify

And updated, he was still confused he saw it in /src/ but just like me he doesn't see it in /lib/

**Comment by vlasenko** [comment]
@justinr1234 I know where is the problem. There are two files, one `Stack.js`, another `stack.js`. The `stack.js` is outdated and just hanged around until I have fully removed `lib` dir in `0.2.0` prior to compilation. Need to add rm -r /lib in `prepublish` task

**Comment by vlasenko** [comment]
@justinr1234 @mitjade I must admit this was hard one to figure out, despite its simple nature. Thank you guys for the help!

**Comment by justinr1234** [comment]
@vlasenko And just like that my non-starter is up and running with spin.js --- thanks for your hard work here. I plan to look into creating a plugin for `native-base`. Are you possibly already working on an example of a UI addin? If so, I might wait until then.

**Comment by vlasenko** [comment]
@justinr1234 I'm not working on UI addin yet. I'm going to work on docs for spin.js. But I think writing plugin should be not hard without docs too. Feel free to ask if you need something, when you decide to write plugin for `NativeBase`

**Comment by vlasenko** [comment]
@justinr1234 After docs I plan to add the feature to install needed libraries for chosen stack via `spin init`. So that this process were automated. Since you are the first who is using `spin.js` outside of starter kit, please tell us what features do you miss the most when you will be ready
